#!/bin/csh
#PBS -S /bin/csh
#PBS -l nodes=1:ppn=24
#PBS -l walltime=2000:00:00
##PBS -o /home/moid/Ashu/TIP3P/out.out
##PBS -e /home/moid/Ashu/TIP3P/out.err
#PBS -N  320

echo "Nodes:"
cat $PBS_NODEFILE
cat $PBS_NODEFILE > temp.1

limit memorylocked unlimited

set NPROCS = `wc -l < $PBS_NODEFILE`
set NNODES = `uniq $PBS_NODEFILE | wc -l`
source /nfsdata/softwares/installed/intel_xece_2016/bin/compilervars.csh intel64

setenv LD_LIBRARY_PATH "/home/jeet/installations/gcc-master/build/lib64:/home/jeet/installations/openmpi-4.1.0/build/lib"
setenv DO_PARALLEL "/home/jeet/installations/openmpi-4.1.0/build/bin/mpirun -np $NPROCS"

#setenv exe "/home/jeet/installations/lammps-test/lammps-master/src/lmp_mpi"
setenv exe "/home/jeet/installations/lammps-test/lammps-master/src/lmp_g++_openmpi"

set curr_dir = $PBS_O_WORKDIR
set temp_dir = $PBS_O_WORKDIR/temp


echo "d0"
                set j="e"
                set tot=0
                foreach i ( `cat  temp.1`  )
                        if ( $j != $i )  then

ssh -n $i mkdir -p $temp_dir/
ssh -n $i cp $curr_dir/*  $temp_dir/
echo "$i " >> t2
ssh -n $i limit >> t2
ssh -n $i limit memorylocked unlimited

                        endif
                        set j="$i"
                        end

cd $temp_dir

$DO_PARALLEL $exe -in in.npt_nve >& log.npt_nve
